namespace SSOLauncher;

/// UI texts for every language the game itself offers. No resx: a plain lookup keeps
/// the Native AOT build free of resource reflection.
///
/// Every T(...) call lists its translations in the order of <see cref="Codes"/>.
/// A short list simply falls back to English, so a miscount degrades instead of crashing.
internal static class L
{
    public static readonly string[] Codes =
        { "en", "de", "sv", "fr", "es", "it", "nl", "pl", "pt", "fi", "da", "no", "hu", "ru" };

    /// Language names shown in the launcher's own language picker.
    public static readonly string[] Names =
    {
        "English", "Deutsch", "Svenska", "Français", "Español", "Italiano", "Nederlands",
        "Polski", "Português", "Suomi", "Dansk", "Norsk", "Magyar", "Русский",
    };

    private static int _index;

    public static string Current => Codes[_index];

    public static void Set(string? code)
    {
        int i = Array.IndexOf(Codes, code ?? "en");
        _index = i < 0 ? 0 : i;
    }

    private static string T(params string[] variants) => _index < variants.Length ? variants[_index] : variants[0];

    // ---------------- navigation ----------------
    public static string Discover => T("Discover", "Entdecken", "Upptäck", "Découvrir", "Descubrir", "Scopri", "Ontdekken", "Odkrywaj", "Descobrir", "Löydä", "Opdag", "Oppdag", "Felfedezés", "Обзор");
    public static string News => T("News", "Neuigkeiten", "Nyheter", "Actualités", "Noticias", "Notizie", "Nieuws", "Aktualności", "Notícias", "Uutiset", "Nyheder", "Nyheter", "Hírek", "Новости");
    public static string Shop => T("Shop", "Shop", "Butik", "Boutique", "Tienda", "Negozio", "Winkel", "Sklep", "Loja", "Kauppa", "Butik", "Butikk", "Bolt", "Магазин");
    public static string Account => T("Account", "Konto", "Konto", "Compte", "Cuenta", "Account", "Account", "Konto", "Conta", "Tili", "Konto", "Konto", "Fiók", "Аккаунт");
    public static string Settings => T("Settings", "Einstellungen", "Inställningar", "Paramètres", "Ajustes", "Impostazioni", "Instellingen", "Ustawienia", "Definições", "Asetukset", "Indstillinger", "Innstillinger", "Beállítások", "Настройки");

    // ---------------- sidebar ----------------
    public static string NotLoggedIn => T("Not logged in", "Nicht angemeldet", "Inte inloggad", "Non connecté", "Sin sesión iniciada", "Non connesso", "Niet ingelogd", "Niezalogowany", "Sessão não iniciada", "Ei kirjautunut", "Ikke logget ind", "Ikke logget inn", "Nincs bejelentkezve", "Вы не вошли");
    public static string Play => T("PLAY", "SPIELEN", "SPELA", "JOUER", "JUGAR", "GIOCA", "SPELEN", "GRAJ", "JOGAR", "PELAA", "SPIL", "SPILL", "JÁTÉK", "ИГРАТЬ");
    public static string Server => T("Server", "Server", "Server", "Serveur", "Servidor", "Server", "Server", "Serwer", "Servidor", "Palvelin", "Server", "Server", "Szerver", "Сервер");
    public static string Checking => T("checking...", "wird geprüft...", "kontrollerar...", "vérification...", "comprobando...", "verifica...", "controleren...", "sprawdzanie...", "a verificar...", "tarkistetaan...", "tjekker...", "sjekker...", "ellenőrzés...", "проверка...");
    public static string Online => T("Online", "Online", "Online", "En ligne", "En línea", "Online", "Online", "Online", "Online", "Verkossa", "Online", "Online", "Online", "В сети");
    public static string Maintenance => T("MAINTENANCE", "WARTUNG", "UNDERHÅLL", "MAINTENANCE", "MANTENIMIENTO", "MANUTENZIONE", "ONDERHOUD", "KONSERWACJA", "MANUTENÇÃO", "HUOLTO", "VEDLIGEHOLDELSE", "VEDLIKEHOLD", "KARBANTARTÁS", "ТЕХРАБОТЫ");
    public static string Disabled => T("disabled", "deaktiviert", "inaktiverad", "désactivé", "desactivado", "disattivato", "uitgeschakeld", "wyłączony", "desativado", "pois käytöstä", "deaktiveret", "deaktivert", "letiltva", "отключён");
    public static string Unknown => T("unknown", "unbekannt", "okänd", "inconnu", "desconocido", "sconosciuto", "onbekend", "nieznany", "desconhecido", "tuntematon", "ukendt", "ukjent", "ismeretlen", "неизвестно");
    public static string GameUpdateRunning => T("game update in progress", "Spiel-Update läuft", "spelet uppdateras", "mise à jour du jeu en cours", "actualización del juego en curso", "aggiornamento del gioco in corso", "game-update bezig", "trwa aktualizacja gry", "atualização do jogo em curso", "pelipäivitys käynnissä", "spilopdatering i gang", "spilloppdatering pågår", "játékfrissítés folyamatban", "идёт обновление игры");
    public static string FreeToPlay => T("Free to play", "Free to play", "Free to play", "Free to play", "Free to play", "Free to play", "Free to play", "Free to play", "Free to play", "Free to play", "Free to play", "Free to play", "Free to play", "Free to play");

    // ---------------- account page ----------------
    public static string SignIn => T("Sign in", "Anmelden", "Logga in", "Connexion", "Iniciar sesión", "Accedi", "Inloggen", "Zaloguj się", "Iniciar sessão", "Kirjaudu", "Log ind", "Logg inn", "Bejelentkezés", "Вход");
    public static string EmailCaption => T("EMAIL", "E-MAIL", "E-POST", "E-MAIL", "CORREO", "EMAIL", "E-MAIL", "E-MAIL", "E-MAIL", "SÄHKÖPOSTI", "E-MAIL", "E-POST", "E-MAIL", "ЭЛ. ПОЧТА");
    public static string PasswordCaption => T("PASSWORD", "PASSWORT", "LÖSENORD", "MOT DE PASSE", "CONTRASEÑA", "PASSWORD", "WACHTWOORD", "HASŁO", "PALAVRA-PASSE", "SALASANA", "ADGANGSKODE", "PASSORD", "JELSZÓ", "ПАРОЛЬ");
    public static string Delete => T("Delete", "Löschen", "Radera", "Supprimer", "Eliminar", "Elimina", "Verwijderen", "Usuń", "Eliminar", "Poista", "Slet", "Slett", "Törlés", "Удалить");
    public static string Show => T("Show", "Anzeigen", "Visa", "Afficher", "Mostrar", "Mostra", "Tonen", "Pokaż", "Mostrar", "Näytä", "Vis", "Vis", "Mutat", "Показать");
    public static string Hide => T("Hide", "Verbergen", "Dölj", "Masquer", "Ocultar", "Nascondi", "Verbergen", "Ukryj", "Ocultar", "Piilota", "Skjul", "Skjul", "Elrejt", "Скрыть");
    public static string RememberEmail => T("Remember email", "E-Mail merken", "Kom ihåg e-post", "Mémoriser l'e-mail", "Recordar correo", "Ricorda email", "E-mail onthouden", "Zapamiętaj e-mail", "Memorizar e-mail", "Muista sähköposti", "Husk e-mail", "Husk e-post", "E-mail megjegyzése", "Запомнить почту");
    public static string SaveLogin => T("Save login securely", "Login sicher speichern", "Spara inloggning säkert", "Enregistrer les identifiants", "Guardar acceso de forma segura", "Salva accesso in sicurezza", "Login veilig opslaan", "Zapisz dane logowania", "Guardar sessão com segurança", "Tallenna kirjautuminen turvallisesti", "Gem login sikkert", "Lagre pålogging sikkert", "Bejelentkezés biztonságos mentése", "Сохранить вход безопасно");
    public static string AutoLogin => T("Auto-login", "Auto-Login", "Automatisk inloggning", "Connexion automatique", "Inicio automático", "Accesso automatico", "Automatisch inloggen", "Automatyczne logowanie", "Início de sessão automático", "Automaattinen kirjautuminen", "Auto-login", "Auto-pålogging", "Automatikus belépés", "Автовход");
    public static string LogIn => T("LOG IN", "ANMELDEN", "LOGGA IN", "SE CONNECTER", "INICIAR SESIÓN", "ACCEDI", "INLOGGEN", "ZALOGUJ", "INICIAR SESSÃO", "KIRJAUDU", "LOG IND", "LOGG INN", "BELÉPÉS", "ВОЙТИ");
    public static string Cancel => T("Cancel", "Abbrechen", "Avbryt", "Annuler", "Cancelar", "Annulla", "Annuleren", "Anuluj", "Cancelar", "Peruuta", "Annuller", "Avbryt", "Mégse", "Отмена");

    // ---------------- discover page ----------------
    public static string BannerFallback => T("Welcome to Jorvik!", "Willkommen in Jorvik!", "Välkommen till Jorvik!", "Bienvenue à Jorvik !", "¡Bienvenido a Jorvik!", "Benvenuto a Jorvik!", "Welkom in Jorvik!", "Witaj w Jorvik!", "Bem-vindo a Jorvik!", "Tervetuloa Jorvikiin!", "Velkommen til Jorvik!", "Velkommen til Jorvik!", "Üdv Jorvikban!", "Добро пожаловать в Йорвик!");
    public static string NewsHint => T("Latest news from starstable.com", "Neuigkeiten von starstable.com", "Senaste nytt från starstable.com", "Dernières actualités de starstable.com", "Últimas noticias de starstable.com", "Ultime notizie da starstable.com", "Laatste nieuws van starstable.com", "Najnowsze wiadomości ze starstable.com", "Últimas notícias de starstable.com", "Uusimmat uutiset sivustolta starstable.com", "Seneste nyt fra starstable.com", "Siste nytt fra starstable.com", "Legfrissebb hírek a starstable.com oldalról", "Последние новости с starstable.com");

    // ---------------- settings page ----------------
    public static string GameClient => T("Game client", "Spiel-Client", "Spelklient", "Client du jeu", "Cliente del juego", "Client di gioco", "Spelclient", "Klient gry", "Cliente do jogo", "Peliasiakas", "Spilklient", "Spillklient", "Játékkliens", "Клиент игры");
    public static string ClientFolderCaption => T("FOLDER CONTAINING SSOCLIENT.EXE", "ORDNER MIT SSOCLIENT.EXE", "MAPP MED SSOCLIENT.EXE", "DOSSIER CONTENANT SSOCLIENT.EXE", "CARPETA CON SSOCLIENT.EXE", "CARTELLA CON SSOCLIENT.EXE", "MAP MET SSOCLIENT.EXE", "FOLDER Z SSOCLIENT.EXE", "PASTA COM SSOCLIENT.EXE", "KANSIO, JOSSA ON SSOCLIENT.EXE", "MAPPE MED SSOCLIENT.EXE", "MAPPE MED SSOCLIENT.EXE", "SSOCLIENT.EXE MAPPÁJA", "ПАПКА С SSOCLIENT.EXE");
    public static string Browse => T("Browse", "Durchsuchen", "Bläddra", "Parcourir", "Examinar", "Sfoglia", "Bladeren", "Przeglądaj", "Procurar", "Selaa", "Gennemse", "Bla gjennom", "Tallózás", "Выбрать");
    public static string Preferences => T("Preferences", "Optionen", "Alternativ", "Préférences", "Preferencias", "Preferenze", "Voorkeuren", "Preferencje", "Preferências", "Valinnat", "Valg", "Valg", "Opciók", "Параметры");
    public static string GameLanguageCaption => T("GAME LANGUAGE", "SPIELSPRACHE", "SPELSPRÅK", "LANGUE DU JEU", "IDIOMA DEL JUEGO", "LINGUA DEL GIOCO", "SPELTAAL", "JĘZYK GRY", "IDIOMA DO JOGO", "PELIN KIELI", "SPILSPROG", "SPILLSPRÅK", "JÁTÉK NYELVE", "ЯЗЫК ИГРЫ");
    public static string LauncherLanguageCaption => T("LAUNCHER LANGUAGE", "LAUNCHER-SPRACHE", "LAUNCHER-SPRÅK", "LANGUE DU LAUNCHER", "IDIOMA DEL LAUNCHER", "LINGUA DEL LAUNCHER", "LAUNCHER-TAAL", "JĘZYK LAUNCHERA", "IDIOMA DO LAUNCHER", "KÄYNNISTIMEN KIELI", "LAUNCHER-SPROG", "LAUNCHER-SPRÅK", "INDÍTÓ NYELVE", "ЯЗЫК ЛАУНЧЕРА");
    public static string VerifyFiles => T("Verify game files before start", "Spieldateien vor dem Start prüfen", "Verifiera spelfiler före start", "Vérifier les fichiers avant le lancement", "Verificar archivos antes de iniciar", "Verifica i file prima dell'avvio", "Spelbestanden controleren voor start", "Sprawdź pliki gry przed startem", "Verificar ficheiros antes de iniciar", "Tarkista pelitiedostot ennen käynnistystä", "Bekræft spilfiler før start", "Kontroller spillfiler før start", "Játékfájlok ellenőrzése indítás előtt", "Проверять файлы игры перед запуском");
    public static string RandomDevice => T("Random device ID", "Zufällige Geräte-ID", "Slumpmässigt enhets-ID", "ID d'appareil aléatoire", "ID de dispositivo aleatorio", "ID dispositivo casuale", "Willekeurige apparaat-ID", "Losowy identyfikator urządzenia", "ID de dispositivo aleatório", "Satunnainen laitetunnus", "Tilfældigt enheds-id", "Tilfeldig enhets-ID", "Véletlenszerű eszközazonosító", "Случайный ID устройства");
    public static string MinimizeToTray => T("Minimize to tray instead of closing", "Beim Schließen in den Infobereich minimieren", "Minimera till aktivitetsfältet i stället för att stänga", "Réduire dans la barre d'état au lieu de fermer", "Minimizar a la bandeja en vez de cerrar", "Riduci a icona invece di chiudere", "Minimaliseren naar systeemvak i.p.v. sluiten", "Minimalizuj do zasobnika zamiast zamykać", "Minimizar para a área de notificação", "Pienennä ilmaisinalueelle sulkemisen sijaan", "Minimér til proceslinjen i stedet for at lukke", "Minimer til systemkurv i stedet for å lukke", "Bezárás helyett a tálcára kicsinyítés", "Сворачивать в трей вместо закрытия");
    public static string StreamerMode => T("Streamer mode (hide my name)", "Streamer-Modus (Name verbergen)", "Streamerläge (dölj mitt namn)", "Mode streamer (masquer mon nom)", "Modo streamer (ocultar mi nombre)", "Modalità streamer (nascondi il nome)", "Streamermodus (naam verbergen)", "Tryb streamera (ukryj nazwę)", "Modo streamer (ocultar o meu nome)", "Suoratoistotila (piilota nimi)", "Streamertilstand (skjul mit navn)", "Streamermodus (skjul navnet mitt)", "Streamer mód (név elrejtése)", "Режим стримера (скрыть имя)");
    public static string TipStreamerMode => T("Replaces the character name, email and account ID with random stand-ins - in the launcher and in the game's window title.", "Ersetzt Charaktername, E-Mail und Konto-ID durch zufällige Platzhalter - im Launcher und im Fenstertitel des Spiels.", "Ersätter karaktärsnamn, e-post och konto-ID med slumpade platshållare - i startaren och i spelets fönstertitel.", "Remplace le nom du personnage, l'e-mail et l'ID de compte par des valeurs aléatoires - dans le launcher et dans le titre de la fenêtre du jeu.", "Sustituye el nombre del personaje, el correo y el ID de cuenta por valores aleatorios, en el launcher y en el título de la ventana del juego.", "Sostituisce nome del personaggio, email e ID account con segnaposto casuali, nel launcher e nel titolo della finestra di gioco.", "Vervangt personagenaam, e-mail en account-ID door willekeurige waarden - in de launcher en in de venstertitel van het spel.", "Zastępuje nazwę postaci, e-mail i ID konta losowymi wartościami - w launcherze i w tytule okna gry.", "Substitui o nome da personagem, o e-mail e o ID de conta por valores aleatórios - no launcher e no título da janela do jogo.", "Korvaa hahmon nimen, sähköpostin ja tilitunnuksen satunnaisilla tiedoilla - käynnistimessä ja pelin ikkunan otsikossa.", "Erstatter karakternavn, e-mail og konto-id med tilfældige pladsholdere - i launcheren og i spillets vinduestitel.", "Erstatter karakternavn, e-post og konto-ID med tilfeldige plassholdere - i launcheren og i spillets vindustittel.", "A karakternevet, az e-mailt és a fiókazonosítót véletlenszerű helyettesítőkre cseréli - az indítóban és a játék ablakcímében is.", "Заменяет имя персонажа, почту и ID аккаунта случайными значениями - в лаунчере и в заголовке окна игры.");
    public static string DarkMode => T("Dark mode", "Dunkler Modus", "Mörkt läge", "Mode sombre", "Modo oscuro", "Modalità scura", "Donkere modus", "Tryb ciemny", "Modo escuro", "Tumma tila", "Mørk tilstand", "Mørk modus", "Sötét mód", "Тёмная тема");
    public static string NotAffiliated => T("not affiliated with Star Stable Entertainment", "nicht mit Star Stable Entertainment verbunden", "inte kopplad till Star Stable Entertainment", "sans lien avec Star Stable Entertainment", "sin relación con Star Stable Entertainment", "non affiliato a Star Stable Entertainment", "niet verbonden aan Star Stable Entertainment", "niepowiązany ze Star Stable Entertainment", "sem ligação à Star Stable Entertainment", "ei liity Star Stable Entertainmentiin", "ikke tilknyttet Star Stable Entertainment", "ikke tilknyttet Star Stable Entertainment", "nem áll kapcsolatban a Star Stable Entertainmenttel", "не связан со Star Stable Entertainment");

    // ---------------- tray ----------------
    public static string TrayShow => T("Show", "Anzeigen", "Visa", "Afficher", "Mostrar", "Mostra", "Tonen", "Pokaż", "Mostrar", "Näytä", "Vis", "Vis", "Mutat", "Показать");
    public static string TrayExit => T("Exit", "Beenden", "Avsluta", "Quitter", "Salir", "Esci", "Afsluiten", "Zakończ", "Sair", "Lopeta", "Afslut", "Avslutt", "Kilépés", "Выход");

    // ---------------- account details ----------------
    public static string FieldUser => T("User", "Benutzer", "Användare", "Utilisateur", "Usuario", "Utente", "Gebruiker", "Użytkownik", "Utilizador", "Käyttäjä", "Bruger", "Bruker", "Felhasználó", "Пользователь");
    public static string FieldStatus => T("Status", "Status", "Status", "Statut", "Estado", "Stato", "Status", "Status", "Estado", "Tila", "Status", "Status", "Állapot", "Статус");
    public static string FieldVerified => T("Verified", "Verifiziert", "Verifierad", "Vérifié", "Verificado", "Verificato", "Geverifieerd", "Zweryfikowany", "Verificado", "Vahvistettu", "Bekræftet", "Bekreftet", "Ellenőrizve", "Подтверждён");
    public static string FieldMinor => T("Minor", "Minderjährig", "Minderårig", "Mineur", "Menor", "Minorenne", "Minderjarig", "Niepełnoletni", "Menor", "Alaikäinen", "Mindreårig", "Mindreårig", "Kiskorú", "Несовершеннолетний");
    public static string FieldSubscription => T("Subscription", "Abo", "Prenumeration", "Abonnement", "Suscripción", "Abbonamento", "Abonnement", "Subskrypcja", "Subscrição", "Tilaus", "Abonnement", "Abonnement", "Előfizetés", "Подписка");
    public static string FieldRegion => T("Region", "Region", "Region", "Région", "Región", "Regione", "Regio", "Region", "Região", "Alue", "Region", "Region", "Régió", "Регион");
    public static string FieldCreated => T("Created", "Erstellt", "Skapad", "Créé", "Creado", "Creato", "Aangemaakt", "Utworzono", "Criado", "Luotu", "Oprettet", "Opprettet", "Létrehozva", "Создан");
    public static string FieldStarCoins => T("Star Coins", "Star Coins", "Star Coins", "Star Coins", "Star Coins", "Star Coins", "Star Coins", "Star Coins", "Star Coins", "Star Coins", "Star Coins", "Star Coins", "Star Coins", "Star Coins");
    public static string Yes => T("yes", "ja", "ja", "oui", "sí", "sì", "ja", "tak", "sim", "kyllä", "ja", "ja", "igen", "да");
    public static string No => T("no", "nein", "nej", "non", "no", "no", "nee", "nie", "não", "ei", "nej", "nei", "nem", "нет");
    public static string NotAvailable => T("n/a", "k. A.", "saknas", "n/d", "n/d", "n/d", "n.v.t.", "brak", "n/d", "ei saat.", "ikke tilgæng.", "ikke tilgj.", "nincs adat", "нет данных");

    // ---------------- status line ----------------
    public static string StepLogin => T("1/4 Logging in...", "1/4 Anmeldung läuft...", "1/4 Loggar in...", "1/4 Connexion...", "1/4 Iniciando sesión...", "1/4 Accesso in corso...", "1/4 Inloggen...", "1/4 Logowanie...", "1/4 A iniciar sessão...", "1/4 Kirjaudutaan...", "1/4 Logger ind...", "1/4 Logger inn...", "1/4 Bejelentkezés...", "1/4 Вход...");
    public static string StepAutoLogin => T("1/4 Auto-login (refresh token)...", "1/4 Auto-Login (Refresh-Token)...", "1/4 Automatisk inloggning...", "1/4 Connexion automatique...", "1/4 Inicio automático...", "1/4 Accesso automatico...", "1/4 Automatisch inloggen...", "1/4 Automatyczne logowanie...", "1/4 Início automático...", "1/4 Automaattinen kirjautuminen...", "1/4 Auto-login...", "1/4 Auto-pålogging...", "1/4 Automatikus belépés...", "1/4 Автовход...");
    public static string StepInit => T("2/4 Initializing account...", "2/4 Konto wird initialisiert...", "2/4 Initierar konto...", "2/4 Initialisation du compte...", "2/4 Inicializando cuenta...", "2/4 Inizializzazione account...", "2/4 Account initialiseren...", "2/4 Inicjowanie konta...", "2/4 A inicializar conta...", "2/4 Alustetaan tiliä...", "2/4 Initialiserer konto...", "2/4 Initialiserer konto...", "2/4 Fiók előkészítése...", "2/4 Инициализация аккаунта...");
    public static string StepConfig => T("3/4 Loading remote config...", "3/4 Remote-Konfiguration wird geladen...", "3/4 Hämtar konfiguration...", "3/4 Chargement de la configuration...", "3/4 Cargando configuración...", "3/4 Caricamento configurazione...", "3/4 Configuratie laden...", "3/4 Wczytywanie konfiguracji...", "3/4 A carregar configuração...", "3/4 Ladataan asetuksia...", "3/4 Henter konfiguration...", "3/4 Henter konfigurasjon...", "3/4 Beállítások betöltése...", "3/4 Загрузка конфигурации...");
    public static string StepServer => T("4/4 Loading game server info...", "4/4 Spielserver-Infos werden geladen...", "4/4 Hämtar serverinfo...", "4/4 Chargement des infos serveur...", "4/4 Cargando datos del servidor...", "4/4 Caricamento dati server...", "4/4 Serverinfo laden...", "4/4 Wczytywanie danych serwera...", "4/4 A carregar dados do servidor...", "4/4 Ladataan palvelintietoja...", "4/4 Henter serverinfo...", "4/4 Henter serverinfo...", "4/4 Szerveradatok betöltése...", "4/4 Загрузка данных сервера...");
    public static string LoginQueue => T("Login queue...", "Login-Warteschlange...", "Inloggningskö...", "File d'attente...", "Cola de acceso...", "Coda di accesso...", "Inlogwachtrij...", "Kolejka logowania...", "Fila de início de sessão...", "Kirjautumisjono...", "Login-kø...", "Innloggingskø...", "Bejelentkezési sor...", "Очередь входа...");
    public static string QueuePosition(object pos) => string.Format(T("In queue... position {0}", "In der Warteschlange... Position {0}", "I kö... plats {0}", "Dans la file... position {0}", "En cola... posición {0}", "In coda... posizione {0}", "In de wachtrij... positie {0}", "W kolejce... pozycja {0}", "Na fila... posição {0}", "Jonossa... sija {0}", "I kø... plads {0}", "I kø... plass {0}", "Sorban... {0}. hely", "В очереди... позиция {0}"), pos);
    public static string StartingClient => T("Starting SSOClient.exe ...", "SSOClient.exe wird gestartet ...", "Startar SSOClient.exe ...", "Lancement de SSOClient.exe ...", "Iniciando SSOClient.exe ...", "Avvio di SSOClient.exe ...", "SSOClient.exe starten ...", "Uruchamianie SSOClient.exe ...", "A iniciar SSOClient.exe ...", "Käynnistetään SSOClient.exe ...", "Starter SSOClient.exe ...", "Starter SSOClient.exe ...", "SSOClient.exe indítása ...", "Запуск SSOClient.exe ...");
    public static string GameRunning(object pid) => string.Format(T("Game running (PID {0}). This launcher can be closed now.", "Spiel läuft (PID {0}). Der Launcher kann jetzt geschlossen werden.", "Spelet körs (PID {0}). Startaren kan stängas nu.", "Jeu lancé (PID {0}). Le launcher peut être fermé.", "Juego en ejecución (PID {0}). Puedes cerrar el launcher.", "Gioco avviato (PID {0}). Puoi chiudere il launcher.", "Spel actief (PID {0}). De launcher kan nu dicht.", "Gra działa (PID {0}). Możesz zamknąć launcher.", "Jogo em execução (PID {0}). Pode fechar o launcher.", "Peli käynnissä (PID {0}). Käynnistimen voi sulkea.", "Spillet kører (PID {0}). Launcheren kan lukkes nu.", "Spillet kjører (PID {0}). Launcheren kan lukkes nå.", "A játék fut (PID {0}). Az indító bezárható.", "Игра запущена (PID {0}). Лаунчер можно закрыть."), pid);
    public static string LoggedInPressPlay => T("Logged in. Press PLAY to start the game.", "Angemeldet. Auf SPIELEN drücken, um zu starten.", "Inloggad. Tryck SPELA för att starta.", "Connecté. Appuyez sur JOUER pour lancer le jeu.", "Sesión iniciada. Pulsa JUGAR para empezar.", "Accesso eseguito. Premi GIOCA per iniziare.", "Ingelogd. Druk op SPELEN om te starten.", "Zalogowano. Naciśnij GRAJ, aby zacząć.", "Sessão iniciada. Carregue em JOGAR para começar.", "Kirjauduttu. Paina PELAA aloittaaksesi.", "Logget ind. Tryk SPIL for at starte.", "Logget inn. Trykk SPILL for å starte.", "Bejelentkezve. Nyomd meg a JÁTÉK gombot.", "Вход выполнен. Нажмите ИГРАТЬ.");
    public static string EnterCredentials => T("Please enter email and password.", "Bitte E-Mail und Passwort eingeben.", "Ange e-post och lösenord.", "Saisissez l'e-mail et le mot de passe.", "Introduce correo y contraseña.", "Inserisci email e password.", "Voer e-mail en wachtwoord in.", "Podaj e-mail i hasło.", "Introduza o e-mail e a palavra-passe.", "Anna sähköposti ja salasana.", "Indtast e-mail og adgangskode.", "Skriv inn e-post og passord.", "Add meg az e-mailt és a jelszót.", "Введите почту и пароль.");
    public static string LoginFirst => T("Please log in first.", "Bitte zuerst anmelden.", "Logga in först.", "Connectez-vous d'abord.", "Inicia sesión primero.", "Effettua prima l'accesso.", "Log eerst in.", "Najpierw się zaloguj.", "Inicie sessão primeiro.", "Kirjaudu ensin sisään.", "Log ind først.", "Logg inn først.", "Előbb jelentkezz be.", "Сначала войдите.");
    public static string Cancelled => T("Cancelled.", "Abgebrochen.", "Avbruten.", "Annulé.", "Cancelado.", "Annullato.", "Geannuleerd.", "Anulowano.", "Cancelado.", "Peruutettu.", "Annulleret.", "Avbrutt.", "Megszakítva.", "Отменено.");
    public static string ErrorPrefix => T("Error: ", "Fehler: ", "Fel: ", "Erreur : ", "Error: ", "Errore: ", "Fout: ", "Błąd: ", "Erro: ", "Virhe: ", "Fejl: ", "Feil: ", "Hiba: ", "Ошибка: ");
    public static string CredentialsChanged => T("Credentials changed - please press LOG IN again.", "Zugangsdaten geändert - bitte erneut ANMELDEN.", "Uppgifterna ändrades - logga in igen.", "Identifiants modifiés - reconnectez-vous.", "Credenciales cambiadas: vuelve a iniciar sesión.", "Credenziali cambiate: accedi di nuovo.", "Gegevens gewijzigd - log opnieuw in.", "Dane się zmieniły - zaloguj się ponownie.", "Credenciais alteradas - inicie sessão de novo.", "Tunnukset muuttuivat - kirjaudu uudelleen.", "Oplysninger ændret - log ind igen.", "Opplysninger endret - logg inn igjen.", "A belépési adatok módosultak - jelentkezz be újra.", "Данные изменились - войдите снова.");
    public static string FileCheckOk => T("File check OK.", "Dateiprüfung OK.", "Filkontroll OK.", "Vérification des fichiers OK.", "Comprobación de archivos correcta.", "Verifica file OK.", "Bestandscontrole OK.", "Sprawdzanie plików OK.", "Verificação de ficheiros OK.", "Tiedostojen tarkistus OK.", "Filkontrol OK.", "Filkontroll OK.", "Fájlellenőrzés rendben.", "Проверка файлов OK.");
    public static string AccountDeleted(string mail) => string.Format(T("Account {0} deleted.", "Konto {0} gelöscht.", "Kontot {0} raderat.", "Compte {0} supprimé.", "Cuenta {0} eliminada.", "Account {0} eliminato.", "Account {0} verwijderd.", "Konto {0} usunięte.", "Conta {0} eliminada.", "Tili {0} poistettu.", "Konto {0} slettet.", "Konto {0} slettet.", "{0} fiók törölve.", "Аккаунт {0} удалён."), mail);
    public static string NoSavedAccount => T("No saved account for this email.", "Kein gespeichertes Konto für diese E-Mail.", "Inget sparat konto för den e-posten.", "Aucun compte enregistré pour cet e-mail.", "No hay cuenta guardada para ese correo.", "Nessun account salvato per questa email.", "Geen opgeslagen account voor dit e-mailadres.", "Brak zapisanego konta dla tego e-maila.", "Sem conta guardada para este e-mail.", "Tälle sähköpostille ei ole tallennettua tiliä.", "Ingen gemt konto for denne e-mail.", "Ingen lagret konto for denne e-posten.", "Nincs mentett fiók ehhez az e-mailhez.", "Для этой почты нет сохранённого аккаунта.");
    public static string AutoLoginFailed => T("Auto-login failed, please log in manually.", "Auto-Login fehlgeschlagen, bitte manuell anmelden.", "Automatisk inloggning misslyckades, logga in manuellt.", "Échec de la connexion automatique, connectez-vous manuellement.", "Fallo el inicio automático, inicia sesión manualmente.", "Accesso automatico non riuscito, accedi manualmente.", "Automatisch inloggen mislukt, log handmatig in.", "Automatyczne logowanie nie powiodło się, zaloguj się ręcznie.", "O início automático falhou, inicie sessão manualmente.", "Automaattinen kirjautuminen epäonnistui, kirjaudu itse.", "Auto-login mislykkedes, log ind manuelt.", "Auto-pålogging mislyktes, logg inn manuelt.", "Az automatikus belépés nem sikerült, jelentkezz be kézzel.", "Автовход не удался, войдите вручную.");

    // ---------------- tooltips ----------------
    public static string TipPlay => T("Start the game (log in first).", "Spiel starten (vorher anmelden).", "Starta spelet (logga in först).", "Lancer le jeu (connectez-vous d'abord).", "Iniciar el juego (inicia sesión antes).", "Avvia il gioco (accedi prima).", "Start het spel (log eerst in).", "Uruchom grę (najpierw zaloguj się).", "Iniciar o jogo (inicie sessão primeiro).", "Käynnistä peli (kirjaudu ensin).", "Start spillet (log ind først).", "Start spillet (logg inn først).", "Játék indítása (előbb jelentkezz be).", "Запустить игру (сначала войдите).");
    public static string TipDelete => T("Remove the saved account for this email.", "Gespeichertes Konto zu dieser E-Mail entfernen.", "Ta bort det sparade kontot för den e-posten.", "Supprimer le compte enregistré pour cet e-mail.", "Eliminar la cuenta guardada de este correo.", "Rimuovi l'account salvato per questa email.", "Verwijder het opgeslagen account voor dit e-mailadres.", "Usuń zapisane konto dla tego e-maila.", "Remover a conta guardada deste e-mail.", "Poista tälle sähköpostille tallennettu tili.", "Fjern den gemte konto for denne e-mail.", "Fjern den lagrede kontoen for denne e-posten.", "A megadott e-mailhez mentett fiók törlése.", "Удалить сохранённый аккаунт для этой почты.");
    public static string TipSavePassword => T("Stores email + password DPAPI-encrypted for this Windows user only.", "Speichert E-Mail + Passwort DPAPI-verschlüsselt, nur für diesen Windows-Benutzer.", "Sparar e-post och lösenord DPAPI-krypterat, bara för den här Windows-användaren.", "Enregistre l'e-mail et le mot de passe chiffrés (DPAPI), pour cet utilisateur Windows uniquement.", "Guarda correo y contraseña cifrados con DPAPI, solo para este usuario de Windows.", "Salva email e password cifrate con DPAPI, solo per questo utente Windows.", "Slaat e-mail en wachtwoord DPAPI-versleuteld op, alleen voor deze Windows-gebruiker.", "Zapisuje e-mail i hasło zaszyfrowane DPAPI, tylko dla tego użytkownika Windows.", "Guarda e-mail e palavra-passe cifrados com DPAPI, só para este utilizador do Windows.", "Tallentaa sähköpostin ja salasanan DPAPI-salattuna vain tälle Windows-käyttäjälle.", "Gemmer e-mail og adgangskode DPAPI-krypteret, kun til denne Windows-bruger.", "Lagrer e-post og passord DPAPI-kryptert, kun for denne Windows-brukeren.", "Az e-mailt és jelszót DPAPI-val titkosítva tárolja, csak ehhez a Windows-felhasználóhoz.", "Сохраняет почту и пароль с шифрованием DPAPI только для этого пользователя Windows.");
    public static string TipAutoLogin => T("Log in automatically on start via refresh token (no password needed).", "Beim Start automatisch per Refresh-Token anmelden (ohne Passwort).", "Logga in automatiskt vid start via refresh-token (utan lösenord).", "Connexion automatique au démarrage via un jeton (sans mot de passe).", "Inicia sesión automáticamente con un token (sin contraseña).", "Accedi automaticamente all'avvio tramite token (senza password).", "Automatisch inloggen bij start via token (zonder wachtwoord).", "Automatyczne logowanie przy starcie przez token (bez hasła).", "Inicia sessão automaticamente através de um token (sem palavra-passe).", "Kirjaudu käynnistyksessä automaattisesti tunnisteella (ilman salasanaa).", "Log automatisk ind ved start via token (uden adgangskode).", "Logg automatisk inn ved start via token (uten passord).", "Automatikus belépés indításkor tokennel (jelszó nélkül).", "Автоматический вход при запуске по токену (без пароля).");
    public static string TipInstallDir => T("Folder containing SSOClient.exe (...\\Star Stable Online\\client).", "Ordner mit SSOClient.exe (...\\Star Stable Online\\client).", "Mapp med SSOClient.exe (...\\Star Stable Online\\client).", "Dossier contenant SSOClient.exe (...\\Star Stable Online\\client).", "Carpeta con SSOClient.exe (...\\Star Stable Online\\client).", "Cartella con SSOClient.exe (...\\Star Stable Online\\client).", "Map met SSOClient.exe (...\\Star Stable Online\\client).", "Folder z SSOClient.exe (...\\Star Stable Online\\client).", "Pasta com SSOClient.exe (...\\Star Stable Online\\client).", "Kansio, jossa on SSOClient.exe (...\\Star Stable Online\\client).", "Mappe med SSOClient.exe (...\\Star Stable Online\\client).", "Mappe med SSOClient.exe (...\\Star Stable Online\\client).", "Az SSOClient.exe mappája (...\\Star Stable Online\\client).", "Папка с SSOClient.exe (...\\Star Stable Online\\client).");
    public static string TipVerify => T("Runs SSOGamelib.exe to verify/repair files, like the official launcher.", "Startet SSOGamelib.exe zum Prüfen/Reparieren der Dateien, wie der offizielle Launcher.", "Kör SSOGamelib.exe för att kontrollera/reparera filer, som den officiella startaren.", "Lance SSOGamelib.exe pour vérifier/réparer les fichiers, comme le launcher officiel.", "Ejecuta SSOGamelib.exe para verificar o reparar archivos, como el launcher oficial.", "Esegue SSOGamelib.exe per verificare/riparare i file, come il launcher ufficiale.", "Voert SSOGamelib.exe uit om bestanden te controleren/repareren, net als de officiële launcher.", "Uruchamia SSOGamelib.exe, aby sprawdzić/naprawić pliki, jak oficjalny launcher.", "Executa o SSOGamelib.exe para verificar/reparar ficheiros, como o launcher oficial.", "Suorittaa SSOGamelib.exe:n tiedostojen tarkistukseen/korjaukseen, kuten virallinen käynnistin.", "Kører SSOGamelib.exe for at kontrollere/reparere filer, som den officielle launcher.", "Kjører SSOGamelib.exe for å sjekke/reparere filer, som den offisielle launcheren.", "Futtatja az SSOGamelib.exe-t a fájlok ellenőrzéséhez/javításához, mint a hivatalos indító.", "Запускает SSOGamelib.exe для проверки и починки файлов, как официальный лаунчер.");
    public static string TipRandomDevice => T("Log in as an unknown device - the server will then require email verification.", "Als unbekanntes Gerät anmelden - der Server verlangt dann eine E-Mail-Bestätigung.", "Logga in som okänd enhet - servern kräver då e-postverifiering.", "Se connecter comme appareil inconnu - le serveur demandera une vérification par e-mail.", "Iniciar sesión como dispositivo desconocido: el servidor pedirá verificación por correo.", "Accedi come dispositivo sconosciuto: il server chiederà una verifica via email.", "Inloggen als onbekend apparaat - de server vraagt dan om e-mailverificatie.", "Logowanie jako nieznane urządzenie - serwer poprosi o weryfikację e-mail.", "Iniciar sessão como dispositivo desconhecido - o servidor pedirá verificação por e-mail.", "Kirjaudu tuntemattomana laitteena - palvelin pyytää sähköpostivarmistusta.", "Log ind som ukendt enhed - serveren kræver så e-mailbekræftelse.", "Logg inn som ukjent enhet - serveren krever da e-postbekreftelse.", "Belépés ismeretlen eszközként - a szerver e-mailes megerősítést kér.", "Вход как с неизвестного устройства - сервер запросит подтверждение по почте.");
    public static string TipCoins => T("Star Coins", "Star Coins", "Star Coins", "Star Coins", "Star Coins", "Star Coins", "Star Coins", "Star Coins", "Star Coins", "Star Coins", "Star Coins", "Star Coins", "Star Coins", "Star Coins");
    public static string TipHorses => T("Horses waiting to be claimed", "Abholbereite Pferde", "Hästar som väntar på att hämtas", "Chevaux à récupérer", "Caballos pendientes de reclamar", "Cavalli da riscattare", "Paarden die klaarstaan", "Konie czekające na odbiór", "Cavalos por reclamar", "Noudettavat hevoset", "Heste, der venter på at blive hentet", "Hester som venter på å hentes", "Átvételre váró lovak", "Лошади, ожидающие получения");
}
